debug:
  autoconfigure: false
  instrumentation: 
    enabled: true
  verbosity: debug
protection:
  enabled: true
  names:
    enabled: true
  code-integrity:
    enabled: true
    objc-calls:
      enabled: true  
    functions:
      enabled: true
    tracing:
      enabled: true
    system-library:
      enabled: true
  control-flow:
    enabled: true
  environment-integrity:
    enabled: true
    debugger:
      enabled: true
    emulator:
      enabled: true
      continue-on-callback: true
    jailbreak:
      enabled: true
      callback: "my_callback"
      continue-on-callback: true
    touch-simulation:
      enabled: true
  arithmetic-operations:
    enabled: true
  data:
    enabled: true
  app-integrity:
    enabled: true
  resources:
    enabled: true
monitor:
  threatcast-key: "eyJ2ZXJzaW9uIjoxLCJrZXkiOiIzNzY2YWRhMTNhODExMDBiYTRmNDI1MjM3YmU5ZTk5MDI1OTRhNTgyNDE0OWQ2MGQiLCJmbGFncyI6eyJoZWFydGJlYXRzIjp0cnVlfSwiZW5kcG9pbnQiOiJyYWRpdHlhbXVsaWFsZXN0YXJpLnRocmVhdGNhc3QuZ3VhcmRzcXVhcmUuY29tIiwiaW50ZWdyYXRpb25LZXkiOiIwZTE3OTYyYzI0Y2I5M2E5N2E1ODUzOWM3YTllMDE4MjdmMmY0NWUzOGNjMjVjZjA4MDlhMzUzZGUwMTI2ZDY5Iiwic2VjcmV0IjoiZGYzYzRkYmY0MWI2ZWU1Zjc3OWEyYzgzMmU1ZWU3ZDZmNzI1M2E0ZjA0ZmViYWExYjIyODk5ZDJiMDE5OGI5ZiJ9" 
license:
  - /Users/rmltech/Documents/GuardSqurare/ixguard-license.txt
 